Feature/nav
wecode-bootcamp-korea/27-1st-DrTart-frontend pull request #1
Opened 2021-11-30 05:09 UTC by sanha-kil

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
사이드 Nav 바 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 사이드 Nav 레이아웃 작성
- position: fixed를 이용하여 화면 왼쪽에 고정되도록 함

2. 토글을 통한 Nav의 확장
- useState로 상태값 관리하여 true값일 때 확장, false값일 때 축소하도록 하였습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- css 애니메이션에 대해 알아보게 되었으며 현재 적용하여 진행중에 있습니다.

<br />

## :: 기타 질문 및 특이 사항
- 아직 없습니다!

2021-11-30 06:16 UTC, younuk23 requested changes
고생하셨습니다 도연님!
- 리뷰사항 반영해주세요
- PR 제목 양식같은 경우 신경써서 맞춰주세요, 지금은 리뷰 드렸지만 다음부터는 포맷에 맞지 않을 경우에는 리뷰진행이 안됩니다!

2021-11-30 06:16 UTC, younuk23 commented on src/components/Nav/Nav.js
> +    <header className="sideHeader">
header tag는 레이아웃상의 header가 아닌 해당 섹션에서 탐색에 도움이 될만한 정보(제목, 로고 등)을 감싸는 태그입니다.
지금 이 상황에서는 적절한 태그는 아닌것 같네요! 어떤 태그 사용할지 다시 한번 고민해보세요!
[참고자료 - MDN](https://developer.mozilla.org/ko/docs/Web/HTML/Element/header)

2021-11-30 06:16 UTC, younuk23 commented on src/components/Nav/Nav.js
> +    <header className="sideHeader">
네스팅을 통해서 이 컴포넌트의 스타일이 다른 컴포넌트에게 영향을 미치지 않도록 컴포넌트의 최상위 태그의 className은 컴포넌트 명과 동일하게 해주세요

2021-11-30 06:16 UTC, younuk23 commented on src/components/Nav/Nav.js
> +        <div className="blockElement" />
blockElement라는 className을 통해서는 이 요소가 어떤 역할을 하는지 알아보기가 힘드네요! 좀 더 의미가 드러나는 네이밍을 해주세요!

2021-11-30 06:16 UTC, younuk23 commented on src/components/Nav/Nav.js
> +      <nav className={`extentionNav ${isToggled ? 'toggledNav' : ''}`}>
display:none을 통해서 요소를 노출시키지 않는 방법도 있지만, 조건부 렌더링을 통해서 애초에 DOM에 삽입을 안하는 방식도 있습니다! 한번 고민해보시고 적용해보시면 좋을 것 같네요!

2021-11-30 06:16 UTC, younuk23 commented on src/components/Nav/Nav.js
> +  };
제 생각에는 isExtended 등의 이름이 조금 더 적합해보이네요 그리고 오히려 함수명자체가 toggle~~~인것이 어떤 값을 담고있는 변수이고, 어떤 역할을 하는 함수인지 명확히 잘 드러나는 것 같네요!

2021-11-30 06:16 UTC, younuk23 commented on src/pages/Main/Main.js
> +      <div>asdasd</div>
테스트용으로 수정한 페이지의 경우에는 다시 원상복구 해주셔야합니다.

그리고 Nav 같은 경우에는 모든 페이지에 있어야 한다면 Router 컴포넌트에서 렌더링해주는것이 좀 더 적합하겠네요 

그리고 아래의 common.css 부분과 같이 리뷰드리자면 body에 직접적으로 스타일링을 부여하는 것은 모든 페이지에 영향을 미치기에 좋지 않습니다.

그리고 Nav가 들어옴으로 인해서 스타일링을 부여한 것 같은데 이것이 common.css에 있게되면 나중에 히스토리를 모르는 개발자입장에서는 찾기도 힘들 것 같네요!

Router에서 import 해주시고 거기에서 다른 div 요소등을 이용해서 padding-left:89px;을 부여해주는것이 한눈에 알아보기에도 좋아보입니다!

이부분 이해안되시면 찾아와서 질문주세요!

2021-11-30 07:24 UTC, younuk23 requested changes
리뷰 확인 및 반영해주세요 도연님~!
그리고 반영 완료된 부분은 코멘트 달아주시면 제가 반영됬는지 좀 더 잘 확인할 수 있습니다!

2021-11-30 07:24 UTC, younuk23 commented on src/components/Nav/Nav.js
> +    <nav className="Nav">
className은 camelCase로 진행해주세요!

2021-11-30 07:24 UTC, younuk23 commented on src/components/Nav/Nav.scss
> +Nav {
tag selector 문법이네요! PR 전에는 반드시 꼼꼼하게 확인하게 제대로 동작하는지도 확인해주세요!

2021-11-30 07:46 UTC, sanha-kil commented on src/components/Nav/Nav.js
> +    <nav className="Nav">
확인했습니다!

2021-11-30 07:47 UTC, sanha-kil commented on src/components/Nav/Nav.scss
> +Nav {
확인했습니다!
로직도 로직인데 이름 정하는게 더 오래걸리네요 ㅎㅎ..

2021-11-30 08:49 UTC, sanha-kil commented on src/components/Nav/Nav.js
> +    <header className="sideHeader">
확인 했습니다!

2021-11-30 08:51 UTC, sanha-kil commented on src/components/Nav/Nav.js
> +        <div className="blockElement" />
space-between으로 요소 배치하기 위한 빈 요소입니다.
이름은 dummyElement로 변경했습니다.

2021-11-30 08:51 UTC, sanha-kil commented on src/components/Nav/Nav.js
> +  };
적용했습니다!

2021-11-30 08:53 UTC, sanha-kil commented on src/pages/Main/Main.js
> +      <div>asdasd</div>
Router에 Nav import 해준 후 본문에 올 페이지들을 위한 레이아웃 스타일을 적용했습니다.

2021-12-01 01:34 UTC, younuk23 approved these changes
첫 머지 축하드립니다 👍

2021-12-01 01:34 UTC, younuk23 commented on src/components/Nav/Nav.js
> +    <nav className="sideNav">
className은 컴포넌트명과 동일하되 카멜케이스인 nav가 적합해보이네요 이부분 다음 브랜치에서 반영해주세요!

2021-12-01 01:34 UTC, merged

2021-12-01 02:47 UTC, sanha-kil commented on src/components/Nav/Nav.js
> +    <nav className="sideNav">
네 감사합니다!