Add: Dr.Tart login layout & logic
wecode-bootcamp-korea/27-1st-DrTart-frontend pull request #3
Opened 2021-12-01 02:06 UTC by howyoujini

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ v] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 
- 입력창에서 데이터를 받아 로그인 버튼을 클릭했을 때 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 Input 컴포넌트의 스타일변화와 조건부 렌더링(span 추가 혹은 제품리스트로 페이지이동)이 일어난다.
- 테스트 방법 : 로그인 input 데이터 입력 (Id : @ 포함, 3글자 이상 Pw : 5글자 이상) 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 로그인 입력창에서 입력값의 변화에 따라 변화,렌더링이 되는 것이 아니라 "클릭이벤트가 발생했을때" 일어나야했다. useState는 입력값의 상태에 따라 자꾸 변화해서 스타일과 span이 자꾸 발생했다. 
- 해결 방법 : useRef 라는 훅을 사용하여 이벤트가 발생했을 때만 렌더링이 가능하게 했다.
<br />

## :: 기타 질문 및 특이 사항
- 부모 컴포넌트에서  isAlertPopId를 useRef로 true, false값을 받아 진행해봤는데 자식컴포넌트에 props로 전달했지만 값이 전달되지 못했던 문제가 발생했습니다. 이를 useState를 활용하니 바로 전달됬는데 어떤 점에서 차이가 발생했는지 궁금합니다.

2021-12-01 03:59 UTC, sanha-kil commented on src/components/BuyNow/BuyNow.js
> +      <button className="closeBtn"></button>
태그 셀프클로징 필요한듯 싶습니다 유진님!

2021-12-01 06:15 UTC, younuk23 approved these changes
고생하셨습니다 유진님 리뷰 확인 및 반영해주세요!

2021-12-01 06:15 UTC, yeonuk-hwang commented on package.json
> +    "eslint": "^7.32.0",
불필요한 dependency가 설치된 것 같네요 삭제해주세요!
eslint 패키지는 CRA에 내장되어있습니다!

2021-12-01 06:15 UTC, yeonuk-hwang commented on src/pages/Login/Input/Input.js
> +/* eslint-disable */
eslint는 코드상에 잠재적인 문제점들을 확인해주는 기능을합니다! disable 시키지말고 확인된 사항들은 수정하는 방향으로 진행해주세요!

2021-12-01 06:15 UTC, yeonuk-hwang commented on src/pages/Login/Input/Input.js
> +const Input = props => {
```suggestion
const Input = ({isAlertPop, placeholder, inputRef}) => {
```
인자자리에서 바로 구조분해할당 할 수 있습니다!

2021-12-01 06:15 UTC, younuk23 commented on src/pages/Login/Input/Input.js
> +          props.isAlertPop ? 'loginInput' && 'alertInput' : 'loginInput'
```suggestion
          props.isAlertPop ? 'alertInput' : 'loginInput'
```
값이 있는 string은 truthy값이기에 무조건 && 구문을 통과하게 되네요!

2021-12-01 06:15 UTC, younuk23 commented on src/pages/Login/Input/Input.scss
> +}
하나의 className으로 네스팅해줘서 혹여라도 className이 겹치는 다른 컴포넌트에게 영향을 주지 않도록 적용해주세요!

2021-12-01 06:15 UTC, younuk23 commented on src/pages/Login/Login.js
> +  const Navigate = useNavigate();
일반적인 변수명은 camelCase로 해주세요 Navigate -> navigate

2021-12-01 06:15 UTC, younuk23 commented on src/pages/Login/Login.js
> +    const idValue = loginData['id'];
loginData 객체에 값을 할당하는 과정은 필요 없을 것 같네요!

2021-12-01 06:15 UTC, younuk23 commented on src/pages/Login/Login.js
> +      idValue.includes('@') && idValue.length > 2 ? true : false;
```suggestion
      idValue.includes('@') && idValue.length > 2
```
이미 비교식의 결과값이 true or false이므로 굳이 삼항연산자로 다시 true or false값을 만들어줄 필요가 없습니다!

2021-12-01 06:15 UTC, younuk23 commented on src/pages/Login/Login.js
> +
```suggestion
   const idValue = idInputRef.current.value;
   return idValue.includes("@") && idValue.length > 2
```

2021-12-01 06:15 UTC, younuk23 commented on src/pages/Login/Login.js
> +    return isPwValid;
위와 마찬가지입니다!

2021-12-01 06:15 UTC, younuk23 commented on src/pages/Login/Login.js
> +
함수명은 idBtn을 벨리데이션하는게 아니라 id 자체를 validation 하는거기에 validateId가 적합해보이네요!

2021-12-01 06:15 UTC, younuk23 commented on src/pages/Login/Login.js
> +    }
```suggestion
   setIsAlertPopId(!validateId());
   setPwAlertPopId(!validatePw());
```
함수 자체의 return 값이 validation의 결과값인 true or false이기에 조건식을 계속 추가할 필요 없이 위와같이 표현 가능해보입니다!

2021-12-01 06:15 UTC, younuk23 commented on src/pages/Login/Login.js
> +    <div className="Login">
camelCase로 해주세요!

2021-12-01 06:15 UTC, younuk23 commented on src/pages/Login/Login.scss
> +      );
```suggestion
      @include flexCenter(column, space-between);
```
인자명은 안적어주셔도 됩니다!

2021-12-01 06:15 UTC, younuk23 commented on src/pages/Login/Login.scss
> +  }
다른 selector끼리는 공백 부여해주세요!

2021-12-01 06:15 UTC, younuk23 requested changes
실수로 Approve 눌러서 Request Change로 수정합니다!

2021-12-01 06:16 UTC, younuk23 commented
부모 컴포넌트에서 isAlertPopId를 useRef로 true, false값을 받아 진행해봤는데 자식컴포넌트에 props로 전달했지만 값이 전달되지 못했던 문제가 발생했습니다. 이를 useState를 활용하니 바로 전달됬는데 어떤 점에서 차이가 발생했는지 궁금합니다.
=>
ref 값 같은 경우에는 props로 전달이 기본적으로 안됩니다! ref값을 props로 전달하려면 forwardRef 라는 함수를 사용해야합니다! forwardRef에 대해서 좀 더 자세히 알아보려면 공식문서 확인해보시면 됩니다!

2021-12-01 06:26 UTC, howyoujini commented on package.json
> +    "eslint": "^7.32.0",
prettier / prettier 에 버전 문제로 [오류가] 생겼어서 eslint 패키지를 다시 설치, 업그레이드 했었습니다!

2021-12-01 06:30 UTC, howyoujini commented on src/pages/Login/Input/Input.js
> +          props.isAlertPop ? 'loginInput' && 'alertInput' : 'loginInput'
그러네요 ㅋㅋㅋㅋㅋ

2021-12-01 06:55 UTC, howyoujini commented on src/pages/Login/Login.js
> +    }
오호! 리팩토링 리뷰 감사합니다 !

2021-12-01 07:22 UTC, howyoujini commented
수정사항 모두 반영하고 push 했습니다 !!

2021-12-01 09:39 UTC, younuk23 requested changes
고생하셨습니다 유진님 반영 안된 부분이 일부 있네요 확인해주세요!

2021-12-01 09:39 UTC, younuk23 commented on package.json
> +    "eslint": "^7.32.0",
이거는 오류메세지 한번 보여주세요 eslint가 이미 내장되어있는데 따로 설치한번 더하면 에러가 발생하는경우를 봤어서요!

2021-12-01 09:39 UTC, younuk23 commented on src/pages/Login/Login.js
> +    <div className="Login">
적용해주세요!!

2021-12-01 09:39 UTC, younuk23 commented on src/pages/Login/Input/Input.js
> +    <div className="Input">
camelCase 적용해주세요
Input -> input 
별개로 input이라는 네이밍이 너무 노멀해서 겹칠 우려가 있어보여서 조금 특정지을 수 있는 이름으로 컴포넌트 이름을 변경하는게 좋아보이네요!

2021-12-01 09:39 UTC, younuk23 commented on src/pages/Login/Login.scss
> +      );
반영해주세요!

2021-12-01 09:39 UTC, younuk23 commented on src/pages/ProductList/ModalBuyNow/ModalBuyNow.js
> +export default ModalBuyNow;
ProductList 부분은 기존에 없었던 부분인데 추가됬네요!!

PR 올리신 후에는 반드시 github에서 File Changed 탭 확인해서 내가 작성한 코드에 실수는 없는지, 내가 의도하지 않은 작업물들이 올라가지 않았는지 확인하는 습관을 들여주세요! PR을 요청할 때의 마음가짐은 실제 내가 등록한 코드가 바로 배포되어서 유저들이 바로 사용하게 된다고 생각하고 해주세요.

브랜치에서 주제로 하고 있는 로그인을 제외한 부분들은 이 브랜치의 작업내역에서 제외해주세요!

2021-12-02 05:15 UTC, younuk23 requested changes
유진님 마이너한 사항들 반영해주세요! 그리고 eslint 패키지 관련 확인 필요해보입니다
한번 찾아와주세요!

2021-12-02 05:15 UTC, younuk23 commented on src/pages/Login/InputInterface/InputInterface.scss
> +  .alertInput {
다른 셀렉터끼리는 공백 부여해주세요!

2021-12-02 05:15 UTC, younuk23 commented on src/pages/Login/InputInterface/InputInterface.scss
> +  }
alertInput안에 네스팅해서 &:focus {} 로 처리가능합니다!

2021-12-02 05:15 UTC, younuk23 commented on src/pages/Login/Login.js
> +  };
다른 함수들끼리도 한줄씩 공백 부여해주세요!

2021-12-02 06:23 UTC, howyoujini commented
확인부탁드립니다 ! 감사합니다 :)

2021-12-02 06:41 UTC, younuk23 approved these changes
LGTM 👍 
머지 축하드립니다~~!!

2021-12-02 06:42 UTC, merged