[27기 김상훈] 회원가입 등록 폼 로직 구현완료 (input 컴포넌트화하여 리팩토링 필요!), 체크박스 로직 구현중...
wecode-bootcamp-korea/27-1st-DrTart-frontend pull request #5
Opened 2021-12-01 05:31 UTC by Ho0on

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ x ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 회원가입을 위한 회원정보 등록 폼 로직과 약관 동의 체크박스 로직 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

1. 회원가입 입력 데이터 유효성 검사 (로직은 완료, input 컴포넌트화하여 리팩토링 필요)
- onBlur를 활용하여 인풋에 변화가 일어날때 유효성 검사 함수를 실행
- 모든 조건을 만족했을때 가입하기 버튼 클릭을 통해 데이터 전송, 회원가입 완료

2. 약관 동의 체크박스 로직 ( 구현 중...)
- 전체선택 박스를 클릭했을 시 모든 체크박스 클릭 활성화
- 필수 체크박스 선택해야만 가입이 가능하도록 구현
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- input의 속성으로 onBlur라는 것을 알게되었습니다
- 컴포넌트화를 통해 반복되는 함수를 간단하게 표현할 수 있다는것을 알게되었습니다

<br />

## :: 기타 질문 및 특이 사항
- 없습니다.

2021-12-02 08:03 UTC, younuk23 commented
package-lock 파일 컨플릭트 발생 되어있습니다.
PR 올리신 후에는 반드시 github에서 File Changed 탭 확인해서 내가 작성한 코드에 실수는 없는지, 내가 의도하지 않은 작업물들이 올라가지 않았는지, 컨플릭트가 발생하진 않았는지 확인하는 습관을 들여주세요!
- lock.json 파일 컨플릭트 해결 방법
    1. package.json 파일의 컨플릭트 해결
    2. `npm install --package-lock-only`
- 참고 링크 : [https://dltlabs.medium.com/package-json-vs-package-lock-json-c8d5deba12cb](https://dltlabs.medium.com/package-json-vs-package-lock-json-c8d5deba12cb)

2021-12-03 02:08 UTC, younuk23 requested changes
첫 PR 고생하셨습니다! 리뷰 확인 및 반영해주세요 상훈님!

2021-12-03 02:08 UTC, yeonuk-hwang commented on src/pages/Signup/Signup.js
> +  }, []);
useCallback을 많이 사용하셨는데 이케이스에는 필요하지 않아 보이네요!!
쓰기만 하면 최적화가 잘 된다고 생각할 수 있지만, 사실 최적화하는데도 비용이 들고 이경우에는 오히려 더 많은 비용을 소모하는 케이스로 보입니다! 아래 아티클 읽으면서 공부해보세요!

[참고자료 - when to useMeme and useCallback](https://goongoguma.github.io/2021/04/26/When-to-useMemo-and-useCallback/)

2021-12-03 02:08 UTC, yeonuk-hwang commented on src/pages/Signup/Signup.js
> +    }
```suggestion
      const newCheckedList = checked ? TERMS_DATA.map(term => term.id) : [];
      setCheckedList(newCheckedList);
    }
```
- 새로운 배열을 만들때는 forEach 보다는 map이 적합합니다.
- setChecked 부분은 계속 반복되고 checked값에 따라서 인자로 들어갈 value만 바뀌면 되기때문에 삼항연산자로 표현하는게 적합해보이네요

2021-12-03 02:08 UTC, yeonuk-hwang commented on src/pages/Signup/Signup.js
> +  );
위 함수랑 비슷한 맥락인것 같아서 고민해보시고 수정해보세요!

2021-12-03 02:08 UTC, yeonuk-hwang commented on src/pages/Signup/Signup.js
> +  function emailValidBlur(e) {
Blur는 함수의 발동시기를 말하는 것 같은데 굳이 이름에 포함되어있을 필요가 없어보입니다!
validateEmail 정도의 함수명이 하는일이 다 드러나는 적합한 이름인 것 같네요 나머지 부분도 확인 및 수정해주세요!

2021-12-03 02:08 UTC, yeonuk-hwang commented on src/pages/Signup/Signup.js
> +  // }
불필요한 주석은 삭제해주세요!
코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.
그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다! 
따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2021-12-03 02:08 UTC, yeonuk-hwang commented on src/pages/Signup/Signup.js
> +  return (
다른 문맥들끼리는 공백을 통해서 가독성에 신경써주세요
return문 위에는 공백이 부여되는게 좋아보이네요

2021-12-03 02:08 UTC, younuk23 commented on src/pages/Signup/Signup.js
> +  const isSameLength = checkedList.length === TERMS_DATA.length ? true : false;
이미 ===의 연산결과가 true false라서 삼항연산자는 불필요해보이네요!

2021-12-03 02:08 UTC, younuk23 commented on src/pages/Signup/Signup.js
> +            id="allChk"
- `id` 보다는 `className` 을 활용해주시기 바랍니다.
- HTML에서  `id` 는 문서 내에서 유일해야 합니다. 이러한 이유로 단일 요소를 다루는 경우 `id`를 사용할 수 있습니다.
- 하지만 정말로 해당 요소에 대한 이벤트나 스타일 핸들링이 프로젝트 전체에서 단 한번만 사용 되는지 충분히 고민해야합니다. 일반적으로 컴포넌트는 재사용 될 수 있기 때문에 같은 요소가 여러번 생성될 수 있습니다. 이러한 이유로 보통의 경우에는 `className` 을 사용합니다.
---
- 아래의 코드와 같이 <label> 안에 <input> 을 중첩시킬 수 있습니다. 이 경우 연관이 암시적이므로 htmlFor 및 id속성이 필요없어 불필요한 속성 사용을 줄일 수 있습니다.

```
<label>Do you like peas?
  <input type="checkbox" name="peas">
</label>
```

2021-12-03 02:08 UTC, younuk23 commented on src/pages/Signup/Signup.js
> +                      key={term.id}
list의 아이템에 최상위 태그에만 key prop이 부여되면 됩니다 여기에는 불필요해보이네요!

2021-12-03 02:08 UTC, younuk23 commented on src/pages/Signup/Signup.js
> +  const isSameLength = checkedList.length === TERMS_DATA.length ? true : false;
유사한 부분들 다 확인 및 수정진행해주시면 됩니다!

2021-12-03 02:08 UTC, younuk23 commented on src/pages/Signup/Signup.js
> +            )}
- 이부분 로직이 반복되는 것 같은데 컴포넌트화 시켜서 valid값에 따라서 validText의 노출여부를 결정시키는 부분을 컴포넌트 안으로 넣어주는것도 좋아보이네요!
- 이부분은 이해 안되시면 스킵하셔도 됩니다 다음주 라이브리뷰시간에 같이 다뤄볼게요!

2021-12-03 02:08 UTC, younuk23 commented on src/pages/Signup/Signup.scss
> +  ul {
- div 태그 처럼 빈번히 사용되는 태그로 스타일을 주는 건 depth에 무관하게 적용되어 의도치 않은 스타일링이 될 수 있습니다. 클래스 셀렉터(ex. `.foo`)를 사용해주세요.
- tag selector는 해당 요소 뿐만 아니라 동일한 태그로 선언된 다른 요소들에게도 영향을 미칠 여지가 너무 많기 때문에 추후 유지보수에 악영향을 미칠 수 있습니다.
- 스타일링을 줄 때는 요소마다 className을 부여하셔서 스타일링을 주시는게 좋습니다.

2021-12-03 02:08 UTC, younuk23 commented on src/pages/Signup/Signup.scss
> +    h3 {
다른 selector끼리 공백 부여해주세요!

2021-12-03 02:08 UTC, younuk23 commented on src/pages/Signup/Signup.scss
> +    .address {
같은 style이라면 각자 다른 className을 부여해주는 것보다는 같은 className을 부여하는식으로 처리해주세요!

2021-12-03 09:37 UTC, Ho0on commented on src/pages/Signup/Signup.js
> +            )}
일단은 킵하겠습니다...!

2021-12-03 10:11 UTC, younuk23 approved these changes
고생하셨습니다 상훈님 첫 리뷰 사항은 마이너한 부분이라서 다음에 반영해주세요!!
첫 머지 축하드립니다 👍

2021-12-03 10:11 UTC, younuk23 commented on src/pages/Signup/Signup.js
> +    !value ? setAddressValid(true) : setAddressValid(false);
```suggestion
    setAddressValid(!value)
```

2021-12-03 10:11 UTC, younuk23 commented on src/pages/Signup/Signup.js
> +      : setCheckedList(checkedList.filter(el => el !== termId));
```suggestion
    const newCheckedList = checked ? [...checkedList, termId] : checkedList.filter(el => el !== termId);
    setCheckedList(newCheckedList);
```
setCheckedList에 인자로 넣는 값만 조건에 따라 변경되면 되기에 위와 같이 표현하는게 더 좋아보이네요! setCheckedList를 두번이나 써줄 필요는 없으니까요!

2021-12-03 10:11 UTC, younuk23 commented on src/pages/Signup/Signup.js
> +      setEmailValid(true);
```suggestion
    if (!value || !value.includes('@')){
      setEmailValid(true);
```

2021-12-03 10:11 UTC, merged

2021-12-07 07:07 UTC, yeonuk-hwang commented on src/pages/Signup/Signup.js
> +            )}
반복되는 부분은 컴포넌트화