[27기 길도연] Image Slide 구현
wecode-bootcamp-korea/27-1st-DrTart-frontend pull request #6
Opened 2021-12-01 08:25 UTC by sanha-kil

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 제품 리스트 페이지에 들어갈 이미지 슬라이드 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 하단 닷버튼 구현
- 닷 버튼을 통해 원하는 이미지를 선택할 수 있습니다.

2. 이미지 변경시 애니메이션 효과 적용
- 조건부 렌더링을 통해 이미지 변경시 컴포넌트 마운트 후 최소한의 애니메이션을 적용하였습니다.

3. 
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 하나의 상태값을 이용해 닷버튼과 이미지를 컨트롤하며 상태값 관리에 대한 이해도를 좀더 높일 수 있었습니다.

<br />

## :: 기타 질문 및 특이 사항
- 없습니다!

2021-12-01 09:53 UTC, younuk23 requested changes
브랜치 잘 나눠서 작업 잘 분리해주시는 것 너무 좋네요 👍 
리뷰 확인 및 반영해주세요 도연님!

2021-12-01 09:53 UTC, younuk23 commented on src/pages/ProductList/ImageSlide/ImageSlide.js
> +        ))}
```suggestion
        {SLIDE_DATA.filter(slide => slide.id === countSlide).map(el => (
          <Slide key={el.id} slideId={el.id} imgUrl={el.imageUrl} />
        ))}
```
el과 같은 광범위한 이름은 지양해주세요, 명확히 어떤 데이터를 나타내는지 이름을 잘 지어주셔야 합니다.
이름짓기가 귀찮고 어려울수 있지만 가장 기본적이면서 가장 중요한 내용이니까 지금부터 이름을 잘 짓는 연습을 하시는게 좋습니다!

2021-12-01 09:53 UTC, younuk23 commented on src/pages/ProductList/ImageSlide/ImageSlide.js
> +        ))}
```suggestion
        {SLIDE_DATA.filter(({id}) => id === countSlide).map(el => (
          <Slide key={el.id} slideId={el.id} imgUrl={el.imageUrl} />
        ))}
```
인자자리에서 바로 구조분해하는식으로도 적용 가능합니다!

2021-12-01 09:53 UTC, younuk23 commented on src/pages/ProductList/ImageSlide/ImageSlide.js
> +  const [countSlide, setCountSlide] = useState(0);
currentSlideId가 좀 더 적합한 이름으로 생각되네요!

2021-12-01 09:53 UTC, younuk23 commented on src/pages/ProductList/ImageSlide/ImageSlide.js
> +            changeSlide={changeSlide}
```suggestion
            changeSlide={() => changeSlide(slide.id)}
```
두개의 props를 받아서 하나의 함수를 동작시키기 위해서 하는 것 같은데 애초에 하나의 함수만 만들어서 props로 전달하는 방식으로 진행하는게 좋아보이네요!

2021-12-01 09:53 UTC, younuk23 commented on src/pages/ProductList/ImageSlide/SlickDot/SlickDot.scss
> +  float: left;
float 속성은 과거에는 많이 쓰였지만 현재에는 유지보수의 불편함과 동작을 예측하기 힘들다는 점 때문에 사용이 잘 되지 않습니다. 
flex,grid 등을 이용해서 표현이 가능한 경우가 대부분이기에 float 사용은 지양해주세요!

2021-12-01 09:53 UTC, younuk23 commented on src/pages/ProductList/ImageSlide/Slide/Slide.scss
> +  .slideContainer {
style을 부여하지 않을거라면 굳이 className을 부여해줄 필요는 없습니다(컴포넌트의 최상위 태그를 제외하고는)

2021-12-01 11:20 UTC, sanha-kil commented on src/pages/ProductList/ImageSlide/ImageSlide.js
> +        ))}
수정하도록 하겠습니다!

2021-12-01 11:34 UTC, sanha-kil commented on src/pages/ProductList/ImageSlide/ImageSlide.js
> +            changeSlide={changeSlide}
changeSlide는 props로 바로 내려줄수 있도록 했습니다.
다만 slideId같은 경우는 currentSlideId와 비교하여 현재 선택된 버튼의 스타일 변경을 위해 props로 내려주었습니다.
혹시 slideId를 따로 내려주지 않는 다면 다른 방식으로 css 변경을 할 수 있는 방법이 있는지 여쭤봐도 될까요?

2021-12-01 11:34 UTC, sanha-kil commented on src/pages/ProductList/ImageSlide/ImageSlide.js
> +  const [countSlide, setCountSlide] = useState(0);
반영했습니다!

2021-12-01 11:35 UTC, sanha-kil commented on src/pages/ProductList/ImageSlide/Slide/Slide.scss
> +  .slideContainer {
확인 했습니다!

2021-12-01 11:35 UTC, sanha-kil commented on src/pages/ProductList/ImageSlide/SlickDot/SlickDot.scss
> +  float: left;
flex로 처리하였습니다!

2021-12-02 05:18 UTC, younuk23 commented on src/pages/ProductList/ImageSlide/ImageSlide.js
> +            changeSlide={changeSlide}
이부분도 isSelected={slideId === currentSlideId} 같이 하나의 props로 전달하는게 컴포넌트가 좀 더 알아보기 쉬워보이네요!!
위에서 미리 비교해서 필요한 결과값만 내려주는 식으로 진행하시면 될 것 같습니다!

마이너한 사항이라서 일단 머지하겠습니다! 다음에 반영해주세요

2021-12-02 05:18 UTC, younuk23 approved these changes
LGTM 👍

2021-12-02 05:18 UTC, merged

2021-12-02 05:58 UTC, sanha-kil commented on src/pages/ProductList/ImageSlide/ImageSlide.js
> +            changeSlide={changeSlide}
네 참고하겠습니다!